### ISSUE TITLE
Border Radius not reflected on zoom only for safari

### ISSUE THREAD

**Issue by vparade** [ricardo-ch/react-easy-crop#332]
**Describe the bug**
I had applied border-radius to img tag but whenever i zoom-in or zoom-out the border Radius is not Reflected, Please check this [Video ](https://www.loom.com/share/cd6d5af1cb6c4f7582079639d4f7aa6d)for reference

My Code:
```tsx
return <div className={Classes.crop_container + ' userProfileCropper'}>                
                   <Cropper
                    image={croppedImage}
                    crop={crop}
                    cropShape='rect'
                    zoom={zoom}
                    showGrid={false}
                    aspect={1}
                    onCropChange={setCrop}
                    onCropComplete={onCropComplete}
                    onZoomChange={setZoom}
                    objectFit='vertical-cover'
                  />
                </div>
                <div className={Classes.iconscroll}>
                <span>
                  <SliderSvgAsync />
                </span>
                <span className={Classes.slidecontainer}>
                  <Slider
                    value={zoom}
                    min={1}
                    max={3}
                    step={0.1}
                    aria-labelledby='Zoom'
                    onChange={(e, zoom) => setZoom(zoom)}
                  />
                </span>
                <span>
                  <SliderSvgAsync />
                </span>
                <span className={Classes.DeleteIcon} onClick={deletePhoto}>
                  <DeleteSvgAsync />
                </span>
              </div>
```

CSS :
```css
.userProfileCropper .reactEasyCrop_Container {
  border-radius: 5px !important;
  -webkit-border-radius: 5px !important;
  -khtml-border-radius: 5px !important;
  -moz-border-radius: 5px !important;
  overflow: hidden !important;
}
```

**Expected behavior**
The border radius should Stay even after zoom-in and zoom-out
